In [1]:
import requests
import json
from pprint import pprint
import pandas as pd
from config import password
from config_db import password_db
from sqlalchemy import create_engine

In [2]:
# import requests from FIFA API to get the World Cup teams information

url = "https://montanaflynn-fifa-world-cup.p.rapidapi.com/teams"

headers = {
    'x-rapidapi-host': "montanaflynn-fifa-world-cup.p.rapidapi.com",
    'x-rapidapi-key': password,
    'accepts': "json"
    }

response = requests.request("GET", url, headers=headers, verify=False)
data = response.json()

print(json.dumps(data, indent=4, sort_keys=True))

C:\Users\u14849\Anaconda3\envs\PythonData\lib\site-packages\urllib3\connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host 'montanaflynn-fifa-world-cup.p.rapidapi.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

[
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "ALG",
        "country_id": 27,
        "created_at": "2014-11-28 11:46:28.162354",
        "id": 1,
        "key": "alg",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Algeria",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.162354",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "EGY",
        "country_id": 28,
        "created_at": "2014-11-28 11:46:28.166625",
        "id": 2,
        "key": "egy",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Egypt",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.166625",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "MAR",
        "country_id": 29,
        "created_at": "2014-11-28 11:46:28.170317",
        "id": 3,
        "key": "mar",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Morocco",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.170317",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "LBY",
        "country_id": 30,
        "created_at": "2014-11-28 11:46:28.174976",
        "id": 4,
        "key": "lby",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Libya",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.174976",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "TUN",
        "country_id": 31,
        "created_at": "2014-11-28 11:46:28.178758",
        "id": 5,
        "key": "tun",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Tunisia",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.178758",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "CPV",
        "country_id": 41,
        "created_at": "2014-11-28 11:46:28.182262",
        "id": 6,
        "key": "cpv",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Cape Verde",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.182262",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "GAM",
        "country_id": 43,
        "created_at": "2014-11-28 11:46:28.185367",
        "id": 7,
        "key": "gam",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Gambia",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.185367",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "GUI",
        "country_id": 45,
        "created_at": "2014-11-28 11:46:28.188873",
        "id": 8,
        "key": "gui",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Guinea",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.188873",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "GNB",
        "country_id": 46,
        "created_at": "2014-11-28 11:46:28.191766",
        "id": 9,
        "key": "gnb",
        "national": "f",
        "since": "",
        "synonyms": "Guinea Bissau",
        "title": "Guinea-Bissau",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.191766",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "LBR",
        "country_id": 47,
        "created_at": "2014-11-28 11:46:28.194584",
        "id": 10,
        "key": "lbr",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Liberia",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.194584",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "MLI",
        "country_id": 48,
        "created_at": "2014-11-28 11:46:28.197957",
        "id": 11,
        "key": "mli",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Mali",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.197957",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "MTN",
        "country_id": 49,
        "created_at": "2014-11-28 11:46:28.201074",
        "id": 12,
        "key": "mtn",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Mauritania",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.201074",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "SEN",
        "country_id": 52,
        "created_at": "2014-11-28 11:46:28.204359",
        "id": 13,
        "key": "sen",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Senegal",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.204359",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "SLE",
        "country_id": 53,
        "created_at": "2014-11-28 11:46:28.207269",
        "id": 14,
        "key": "sle",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Sierra Leone",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.207269",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "BEN",
        "country_id": 39,
        "created_at": "2014-11-28 11:46:28.225637",
        "id": 15,
        "key": "ben",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Benin",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.225637",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "BFA",
        "country_id": 40,
        "created_at": "2014-11-28 11:46:28.230361",
        "id": 16,
        "key": "bfa",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Burkina Faso",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.230361",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "CIV",
        "country_id": 42,
        "created_at": "2014-11-28 11:46:28.234383",
        "id": 17,
        "key": "civ",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "C\u00f4te d'Ivoire",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.234383",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "GHA",
        "country_id": 44,
        "created_at": "2014-11-28 11:46:28.237881",
        "id": 18,
        "key": "gha",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Ghana",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.237881",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "NIG",
        "country_id": 50,
        "created_at": "2014-11-28 11:46:28.240924",
        "id": 19,
        "key": "nig",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Niger",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.240924",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "NGA",
        "country_id": 51,
        "created_at": "2014-11-28 11:46:28.243644",
        "id": 20,
        "key": "nga",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Nigeria",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.243644",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "TOG",
        "country_id": 54,
        "created_at": "2014-11-28 11:46:28.246526",
        "id": 21,
        "key": "tog",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Togo",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.246526",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "CMR",
        "country_id": 19,
        "created_at": "2014-11-28 11:46:28.248988",
        "id": 22,
        "key": "cmr",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Cameroon",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.248988",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "CTA",
        "country_id": 20,
        "created_at": "2014-11-28 11:46:28.251678",
        "id": 23,
        "key": "cta",
        "national": "f",
        "since": "",
        "synonyms": "C. Afr. Rep.",
        "title": "Central African Republic",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.251678",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "CHA",
        "country_id": 21,
        "created_at": "2014-11-28 11:46:28.254512",
        "id": 24,
        "key": "cha",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Chad",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.254512",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "CGO",
        "country_id": 22,
        "created_at": "2014-11-28 11:46:28.257368",
        "id": 25,
        "key": "cgo",
        "national": "f",
        "since": "",
        "synonyms": "Congo-Brazzaville|Congo-Brazz.",
        "title": "Congo",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.257368",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "COD",
        "country_id": 23,
        "created_at": "2014-11-28 11:46:28.260376",
        "id": 26,
        "key": "cod",
        "national": "f",
        "since": "",
        "synonyms": "Congo-Kinshasa|Congo-Kinsh.",
        "title": "Congo DR",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.260376",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "EQG",
        "country_id": 24,
        "created_at": "2014-11-28 11:46:28.262922",
        "id": 27,
        "key": "eqg",
        "national": "f",
        "since": "",
        "synonyms": "Equat. Guinea",
        "title": "Equatorial Guinea",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.262922",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "GAB",
        "country_id": 25,
        "created_at": "2014-11-28 11:46:28.265713",
        "id": 28,
        "key": "gab",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Gabon",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.265713",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "STP",
        "country_id": 26,
        "created_at": "2014-11-28 11:46:28.268679",
        "id": 29,
        "key": "stp",
        "national": "f",
        "since": "",
        "synonyms": "S\u00e3o Tom\u00e9 e Pr\u00edncipe|S\u00e3o Tom\u00e9/Pr.",
        "title": "S\u00e3o Tom\u00e9 and Pr\u00edncipe",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.268679",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "BDI",
        "country_id": 1,
        "created_at": "2014-11-28 11:46:28.271243",
        "id": 30,
        "key": "bdi",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Burundi",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.271243",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "DJI",
        "country_id": 3,
        "created_at": "2014-11-28 11:46:28.274096",
        "id": 31,
        "key": "dji",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Djibouti",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.274096",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "ERI",
        "country_id": 4,
        "created_at": "2014-11-28 11:46:28.276895",
        "id": 32,
        "key": "eri",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Eritrea",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.276895",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "ETH",
        "country_id": 5,
        "created_at": "2014-11-28 11:46:28.279494",
        "id": 33,
        "key": "eth",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Ethiopia",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.279494",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "KEN",
        "country_id": 6,
        "created_at": "2014-11-28 11:46:28.281804",
        "id": 34,
        "key": "ken",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Kenya",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.281804",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "RWA",
        "country_id": 11,
        "created_at": "2014-11-28 11:46:28.284190",
        "id": 35,
        "key": "rwa",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Rwanda",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.284190",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "SOM",
        "country_id": 13,
        "created_at": "2014-11-28 11:46:28.286661",
        "id": 36,
        "key": "som",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Somalia",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.286661",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "SSD",
        "country_id": 32,
        "created_at": "2014-11-28 11:46:28.289183",
        "id": 37,
        "key": "ssd",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "South Sudan",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.289183",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "SDN",
        "country_id": 33,
        "created_at": "2014-11-28 11:46:28.291417",
        "id": 38,
        "key": "sdn",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Sudan",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.291417",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "TAN",
        "country_id": 14,
        "created_at": "2014-11-28 11:46:28.293760",
        "id": 39,
        "key": "tan",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Tanzania",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.293760",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "UGA",
        "country_id": 15,
        "created_at": "2014-11-28 11:46:28.296693",
        "id": 40,
        "key": "uga",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Uganda",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.296693",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "ZAN",
        "country_id": 14,
        "created_at": "2014-11-28 11:46:28.299144",
        "id": 41,
        "key": "zan",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Zanzibar",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.299144",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "ANG",
        "country_id": 18,
        "created_at": "2014-11-28 11:46:28.301527",
        "id": 42,
        "key": "ang",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Angola",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.301527",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "BOT",
        "country_id": 35,
        "created_at": "2014-11-28 11:46:28.303994",
        "id": 43,
        "key": "bot",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Botswana",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.303994",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "COM",
        "country_id": 2,
        "created_at": "2014-11-28 11:46:28.306156",
        "id": 44,
        "key": "com",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Comoros",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.306156",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "LES",
        "country_id": 36,
        "created_at": "2014-11-28 11:46:28.309399",
        "id": 45,
        "key": "les",
        "national": "f",
        "since": "",
        "synonyms": "",
        "title": "Lesotho",
        "title2": "",
        "updated_at": "2014-11-28 11:46:28.309399",
        "web": ""
    },
    {
        "address": "",
        "assoc_id": "",
        "city_id": "",
        "club": "f",
        "code": "MRI",
        "country_id": 9,
        "created_at": "2014-11-28 11:46:28.312741",
        "id": 46,

In [3]:
# Check how much data contains in worldcup teams API

teams_code = data[0]["title"]
print(teams_code)

teamscount = len(data)
teamscount

Algeria

222

In [4]:
# Append the required information in lists

code = []
title = []
key = []


id = 0
for each in range(teamscount):
    data = response.json()
    code.append(data[id]['code'])
    title.append(data[id]['title'])
    key.append(data[id]['key'])
    
    id +=1
    
print(f"{code}{title}{key}")

['ALG', 'EGY', 'MAR', 'LBY', 'TUN', 'CPV', 'GAM', 'GUI', 'GNB', 'LBR', 'MLI', 'MTN', 'SEN', 'SLE', 'BEN', 'BFA', 'CIV', 'GHA', 'NIG', 'NGA', 'TOG', 'CMR', 'CTA', 'CHA', 'CGO', 'COD', 'EQG', 'GAB', 'STP', 'BDI', 'DJI', 'ERI', 'ETH', 'KEN', 'RWA', 'SOM', 'SSD', 'SDN', 'TAN', 'UGA', 'ZAN', 'ANG', 'BOT', 'COM', 'LES', 'MRI', 'MAD', 'MWI', 'MOZ', 'NAM', 'SEY', 'RSA', 'SWZ', 'ZAM', 'ZIM', 'REU', 'KAZ', 'AFG', 'BAN', 'BHU', 'IND', 'KGZ', 'MDV', 'NEP', 'PAK', 'SRI', 'TJK', 'TKM', 'UZB', 'CHN', 'HKG', 'JPN', 'PRK', 'KOR', 'MAC', 'MGL', 'TPE', 'BRU', 'CAM', 'IDN', 'LAO', 'MAS', 'MYA', 'PHI', 'SIN', 'THA', 'TLS', 'VIE', 'AIA', 'ATG', 'ABW', 'BAH', 'BRB', 'BMU', 'VGB', 'CYM', 'CUB', 'CUW', 'DMA', 'DOM', 'GRN', 'HAI', 'JAM', 'MSR', 'PUR', 'SKN', 'LCA', 'VIN', 'TRI', 'TCA', 'VIR', 'BON', 'GPE', 'MTQ', 'MAF', 'SXM', 'HON', 'CRC', 'SLV', 'PAN', 'GUA', 'BLZ', 'NCA', 'AUT', 'BEL', 'CYP', 'GER', 'EST', 'ESP', 'FIN', 'FRA', 'GRE', 'IRL', 'ITA', 'LUX', 'MLT', 'NED', 'POR', 'SVK', 'SVN', 'BUL', 'DEN', 'LVA', 'LTU', 'POL', 'ROU', 'SWE', 'CZE', 'HUN', 'AND', 'ALB', 'BLR', 'SUI', 'CRO', 'SRB', 'RUS', 'TUR', 'UKR', 'MKD', 'NOR', 'ISL', 'BIH', 'LIE', 'MNE', 'MDA', 'SMR', 'GEO', 'ARM', 'AZE', 'ENG', 'SCO', 'WAL', 'NIR', 'FRO', 'GIB', 'ISR', 'BHR', 'IRN', 'IRQ', 'JOR', 'KUW', 'LIB', 'OMA', 'PLE', 'QAT', 'KSA', 'SYR', 'UAE', 'YEM', 'MEX', 'USA', 'CAN', 'AUS', 'GUM', 'MNP', 'ASM', 'COK', 'FIJ', 'NCL', 'NZL', 'PNG', 'SAM', 'SOL', 'TAH', 'TGA', 'VAN', 'KIR', 'NIU', 'TUV', 'ARG', 'BRA', 'CHI', 'PAR', 'URU', 'COL', 'ECU', 'PER', 'VEN', 'BOL', 'GUY', 'SUR', 'GYF']['Algeria', 'Egypt', 'Morocco', 'Libya', 'Tunisia', 'Cape Verde', 'Gambia', 'Guinea', 'Guinea-Bissau', 'Liberia', 'Mali', 'Mauritania', 'Senegal', 'Sierra Leone', 'Benin', 'Burkina Faso', "Côte d'Ivoire", 'Ghana', 'Niger', 'Nigeria', 'Togo', 'Cameroon', 'Central African Republic', 'Chad', 'Congo', 'Congo DR', 'Equatorial Guinea', 'Gabon', 'São Tomé and Príncipe', 'Burundi', 'Djibouti', 'Eritrea', 'Ethiopia', 'Kenya', 'Rwanda', 'Somalia', 'South Sudan', 'Sudan', 'Tanzania', 'Uganda', 'Zanzibar', 'Angola', 'Botswana', 'Comoros', 'Lesotho', 'Mauritius', 'Madagascar', 'Malawi', 'Mozambique', 'Namibia', 'Seychelles', 'South Africa', 'Swaziland', 'Zambia', 'Zimbabwe', 'Réunion', 'Kazakhstan', 'Afghanistan', 'Bangladesh', 'Bhutan', 'India', 'Kyrgyzstan', 'Maldives', 'Nepal', 'Pakistan', 'Sri Lanka', 'Tajikistan', 'Turkmenistan', 'Uzbekistan', 'China', 'Hong Kong', 'Japan', 'North Korea', 'South Korea', 'Macau', 'Mongolia', 'Taiwan', 'Brunei', 'Cambodia', 'Indonesia', 'Laos', 'Malaysia', 'Myanmar', 'Philippines', 'Singapore', 'Thailand', 'Timor-Leste', 'Vietnam', 'Anguilla', 'Antigua and Barbuda', 'Aruba', 'Bahamas', 'Barbados', 'Bermuda', 'British Virgin Islands', 'Cayman Islands', 'Cuba', 'Curaçao', 'Dominica', 'Dominican Republic', 'Grenada', 'Haiti', 'Jamaica', 'Montserrat', 'Puerto Rico', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Trinidad and Tobago', 'Turks and Caicos Islands', 'United States Virgin Islands', 'Bonaire', 'Guadeloupe', 'Martinique', 'Saint Martin', 'Sint Maarten', 'Honduras', 'Costa Rica', 'El Salvador', 'Panama', 'Guatemala', 'Belize', 'Nicaragua', 'Austria', 'Belgium', 'Cyprus', 'Germany', 'Estonia', 'Spain', 'Finland', 'France', 'Greece', 'Ireland', 'Italy', 'Luxembourg', 'Malta', 'Netherlands', 'Portugal', 'Slovakia', 'Slovenia', 'Bulgaria', 'Denmark', 'Latvija', 'Lithuania', 'Poland', 'Romania', 'Sweden', 'Czech Republic', 'Hungary', 'Andorra', 'Albania', 'Belarus', 'Switzerland', 'Croatia', 'Serbia', 'Russia', 'Turkey', 'Ukraine', 'Macedonia', 'Norway', 'Iceland', 'Bosnia-Herzegovina', 'Liechtenstein', 'Montenegro', 'Moldova', 'San Marino', 'Georgia', 'Armenia', 'Azerbaijan', 'England', 'Scotland', 'Wales', 'Northern Ireland', 'Faroe Islands', 'Gibraltar', 'Israel', 'Bahrain', 'Iran', 'Iraq', 'Jordan', 'Kuwait', 'Lebanon', 'Oman', 'Palestine', 'Qatar', 'Saudi Arabia', 'Syria', 'United Arab Emirates', 'Yemen', 'Mexico', 'United States', 'Canada', 'Australia', 'Guam', 'Northern Mariana Islands', 'American Samoa', 'Cook Islands', 'Fiji', 'New Caledonia', 'New Zealand', 'Papua New Guinea', 'Samoa', 'Solomon Islands', 'Tahiti', 'Tonga', 'Vanuatu', 'Kiribati', 'Niue', 'Tuvalu', 'Argentina', 'Brazil', 'Chile', 'Paraguay', 'Uruguay', 'Colombia', 'Ecuador', 'Peru', 'Venezuela', 'Bolivia', 'Guyana', 'Suriname', 'French Guiana']['alg', 'egy', 'mar', 'lby', 'tun', 'cpv', 'gam', 'gui', 'gnb', 'lbr', 'mli', 'mtn', 'sen', 'sle', 'ben', 'bfa', 'civ', 'gha', 'nig', 'nga', 'tog', 'cmr', 'cta', 'cha', 'cgo', 'cod', 'eqg', 'gab', 'stp', 'bdi', 'dji', 'eri', 'eth', 'ken', 'rwa', 'som', 'ssd', 'sdn', 'tan', 'uga', 'zan', 'ang', 'bot', 'com', 'les', 'mri', 'mad', 'mwi', 'moz', 'nam', 'sey', 'rsa', 'swz', 'zam', 'zim', 'reu', 'kaz', 'afg', 'ban', 'bhu', 'ind', 'kgz', 'mdv', 'nep', 'pak', 'sri', 'tjk', 'tkm', 'uzb', 'chn', 'hkg', 'jpn', 'prk', 'kor', 'mac', 'mgl', 'tpe', 'bru', 'cam', 'idn', 'lao', 'mas', 'mya', 'phi', 'sin', 'tha', 'tls', 'vie', 'aia', 'atg', 'abw', 'bah', 'brb', 'bmu', 'vgb', 'cym', 'cub', 'cuw', 'dma', 'dom', 'grn', 'hai', 'jam', 'msr', 'pur', 'skn', 'lca', 'vin', 'tri', 'tca', 'vir', 'bon', 'gpe', 'mtq', 'maf', 'sxm', 'hon', 'crc', 'slv', 'pan', 'gua', 'blz', 'nca', 'aut', 'bel', 'cyp', 'ger', 'est', 'esp', 'fin', 'fra', 'gre', 'irl', 'ita', 'lux', 'mlt', 'ned', 'por', 'svk', 'svn', 'bul', 'den', 'lva', 'ltu', 'pol', 'rou', 'swe', 'cze', 'hun', 'and', 'alb', 'blr', 'sui', 'cro', 'srb', 'rus', 'tur', 'ukr', 'mkd', 'nor', 'isl', 'bih', 'lie', 'mne', 'mda', 'smr', 'geo', 'arm', 'aze', 'eng', 'sco', 'wal', 'nir', 'fro', 'gib', 'isr', 'bhr', 'irn', 'irq', 'jor', 'kuw', 'lib', 'oma', 'ple', 'qat', 'ksa', 'syr', 'uae', 'yem', 'mex', 'usa', 'can', 'aus', 'gum', 'mnp', 'asm', 'cok', 'fij', 'ncl', 'nzl', 'png', 'sam', 'sol', 'tah', 'tga', 'van', 'kir', 'niu', 'tuv', 'arg', 'bra', 'chi', 'par', 'uru', 'col', 'ecu', 'per', 'ven', 'bol', 'guy', 'sur', 'gyf']

In [5]:
# get data into dataframe

team_df = pd.DataFrame({
    "code":code,
    "title":title,
    "key":key,
                         })

team_df

    code          title  key
0    ALG        Algeria  alg
1    EGY          Egypt  egy
2    MAR        Morocco  mar
3    LBY          Libya  lby
4    TUN        Tunisia  tun
..   ...            ...  ...
217  VEN      Venezuela  ven
218  BOL        Bolivia  bol
219  GUY         Guyana  guy
220  SUR       Suriname  sur
221  GYF  French Guiana  gyf

[222 rows x 3 columns]

In [6]:
# rename the code field into country so it can join with other datasets

team_df_renamed = team_df

team_df_renamed1 = team_df_renamed.rename(columns={'code':'Country'})

team_df_renamed1

    Country          title  key
0       ALG        Algeria  alg
1       EGY          Egypt  egy
2       MAR        Morocco  mar
3       LBY          Libya  lby
4       TUN        Tunisia  tun
..      ...            ...  ...
217     VEN      Venezuela  ven
218     BOL        Bolivia  bol
219     GUY         Guyana  guy
220     SUR       Suriname  sur
221     GYF  French Guiana  gyf

[222 rows x 3 columns]

In [7]:
# Get players data from csv file extracted sqlite manually

players_data = pd.read_csv("Resources/Players.csv")
players_data

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154
...,...,...,...,...,...,...,...
11055,11071,26357,Zoumana Camara,2488,1979-04-03 00:00:00,182.88,168
11056,11072,111182,Zsolt Laczko,164680,1986-12-18 00:00:00,182.88,176
11057,11073,36491,Zsolt Low,111191,1979-04-29 00:00:00,180.34,154
11058,11074,35506,Zurab Khizanishvili,47058,1981-10-06 00:00:00,185.42,172
11059,11075,39902,Zvjezdan Misimovic,102359,1982-06-05 00:00:00,180.34,176

In [8]:
# transform players data by dropping unecessary columns

players_data = players_data.drop(['id','player_fifa_api_id'],axis = 1)
players_data

       player_api_id          player_name             birthday  height  weight
0             505942   Aaron Appindangoye  1992-02-29 00:00:00  182.88     187
1             155782      Aaron Cresswell  1989-12-15 00:00:00  170.18     146
2             162549          Aaron Doran  1991-05-13 00:00:00  170.18     163
3              30572        Aaron Galindo  1982-05-08 00:00:00  182.88     198
4              23780         Aaron Hughes  1979-11-08 00:00:00  182.88     154
...              ...                  ...                  ...     ...     ...
11055          26357       Zoumana Camara  1979-04-03 00:00:00  182.88     168
11056         111182         Zsolt Laczko  1986-12-18 00:00:00  182.88     176
11057          36491            Zsolt Low  1979-04-29 00:00:00  180.34     154
11058          35506  Zurab Khizanishvili  1981-10-06 00:00:00  185.42     172
11059          39902   Zvjezdan Misimovic  1982-06-05 00:00:00  180.34     176

[11060 rows x 5 columns]

In [9]:
# Set index for players dataset

players_data_new1 = players_data.set_index('player_api_id')
players_data_new1

                       player_name             birthday  height  weight
player_api_id
505942          Aaron Appindangoye  1992-02-29 00:00:00  182.88     187
155782             Aaron Cresswell  1989-12-15 00:00:00  170.18     146
162549                 Aaron Doran  1991-05-13 00:00:00  170.18     163
30572                Aaron Galindo  1982-05-08 00:00:00  182.88     198
23780                 Aaron Hughes  1979-11-08 00:00:00  182.88     154
...                            ...                  ...     ...     ...
26357               Zoumana Camara  1979-04-03 00:00:00  182.88     168
111182                Zsolt Laczko  1986-12-18 00:00:00  182.88     176
36491                    Zsolt Low  1979-04-29 00:00:00  180.34     154
35506          Zurab Khizanishvili  1981-10-06 00:00:00  185.42     172
39902           Zvjezdan Misimovic  1982-06-05 00:00:00  180.34     176

[11060 rows x 4 columns]

In [10]:
# pull players attributes dataset adquired from csv

playerattr_df = pd.read_csv("Resources/Players_Attributes.csv")
playerattr_df

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,attacking_work_rate,defensive_work_rate,short_passing,dribbling,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,medium,medium,61.0,51.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,medium,medium,61.0,51.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,medium,medium,61.0,51.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,medium,medium,60.0,50.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,medium,medium,60.0,50.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183973,183974,102359,39902,2009-08-30 00:00:00,83.0,85.0,medium,low,89.0,84.0,...,88.0,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0
183974,183975,102359,39902,2009-02-22 00:00:00,78.0,80.0,medium,low,84.0,85.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183975,183976,102359,39902,2008-08-30 00:00:00,77.0,80.0,medium,low,84.0,85.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183976,183977,102359,39902,2007-08-30 00:00:00,78.0,81.0,medium,low,86.0,87.0,...,88.0,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0
183977,183978,102359,39902,2007-02-22 00:00:00,80.0,81.0,medium,low,88.0,87.0,...,88.0,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0

In [11]:
# transform player attribute dataset

playerattr_df.dropna(axis=0, how='any', inplace=True)
playerattr_df.drop(["id","player_fifa_api_id","attacking_work_rate", "defensive_work_rate","short_passing","dribbling","long_passing",
                    "ball_control","acceleration","sprint_speed","agility","reactions","balance","jumping","stamina",
                    "strength","aggression","interceptions","positioning","vision","penalties","marking","standing_tackle","sliding_tackle"],
                   axis = 1, inplace = True)
playerattr_df.head()

,player_api_id,date,overall_rating,potential,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,505942,2016-02-18 00:00:00,67.0,71.0,6.0,11.0,10.0,8.0,8.0
1,505942,2015-11-19 00:00:00,67.0,71.0,6.0,11.0,10.0,8.0,8.0
2,505942,2015-09-21 00:00:00,62.0,66.0,6.0,11.0,10.0,8.0,8.0
3,505942,2015-03-20 00:00:00,61.0,65.0,5.0,10.0,9.0,7.0,7.0
4,505942,2007-02-22 00:00:00,61.0,65.0,5.0,10.0,9.0,7.0,7.0

In [12]:
# continue with ETL work for player attribute

playerattr_df = playerattr_df.set_index('player_api_id')
playerattr_df

,date,overall_rating,potential,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
player_api_id,,,,,,,,
505942,2016-02-18 00:00:00,67.0,71.0,6.0,11.0,10.0,8.0,8.0
505942,2015-11-19 00:00:00,67.0,71.0,6.0,11.0,10.0,8.0,8.0
505942,2015-09-21 00:00:00,62.0,66.0,6.0,11.0,10.0,8.0,8.0
505942,2015-03-20 00:00:00,61.0,65.0,5.0,10.0,9.0,7.0,7.0
505942,2007-02-22 00:00:00,61.0,65.0,5.0,10.0,9.0,7.0,7.0
...,...,...,...,...,...,...,...,...
39902,2009-08-30 00:00:00,83.0,85.0,9.0,20.0,84.0,20.0,20.0
39902,2009-02-22 00:00:00,78.0,80.0,9.0,20.0,73.0,20.0,20.0
39902,2008-08-30 00:00:00,77.0,80.0,9.0,20.0,73.0,20.0,20.0
39902,2007-08-30 00:00:00,78.0,81.0,9.0,20.0,73.0,20.0,20.0
39902,2007-02-22 00:00:00,80.0,81.0,9.0,9.0,78.0,7.0,15.0

In [13]:
# get the latest date for each player id, so it can be uniquely identified (only interested on most recent information)

playerattr_df_new = playerattr_df.sort_values('date').groupby('player_api_id').max()
playerattr_df_new

,date,overall_rating,potential,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
player_api_id,,,,,,,,
2625,2015-01-16 00:00:00,63.0,64.0,14.0,24.0,67.0,24.0,24.0
2752,2015-10-16 00:00:00,72.0,72.0,12.0,7.0,8.0,10.0,16.0
2768,2016-03-17 00:00:00,75.0,75.0,12.0,21.0,56.0,21.0,21.0
2770,2013-07-05 00:00:00,74.0,81.0,12.0,21.0,83.0,21.0,21.0
2790,2010-08-30 00:00:00,73.0,77.0,8.0,21.0,73.0,21.0,21.0
...,...,...,...,...,...,...,...,...
744907,2016-06-09 00:00:00,53.0,67.0,9.0,14.0,13.0,12.0,9.0
746419,2016-05-12 00:00:00,59.0,66.0,7.0,10.0,7.0,9.0,9.0
748432,2016-05-12 00:00:00,58.0,68.0,8.0,8.0,12.0,12.0,6.0
750435,2016-04-14 00:00:00,60.0,74.0,9.0,10.0,8.0,10.0,11.0
750584,2016-05-19 00:00:00,58.0,66.0,8.0,9.0,13.0,11.0,13.0

In [14]:
# extract data from penalty dataset (this is the key information for our use case. Intention is to evaluate Goalkeepers
# in corresponding teams with their performance)

keeper_df = pd.read_csv("Resources/GKPenalty.csv")
keeper_df

,Goalkeeper,Current team,Born,Country,NotConceded,Conceded,PKsFaced,Saves
0,Karlo Letica,Club Brugge,1997.0,CRO,3.0,2.0,5,60.00%
1,Yuri Lodygin,Zenit,1990.0,RUS,7.0,6.0,13,53.85%
2,Diego Alves,Valencia,1985.0,BRA,25.0,31.0,56,44.64%
3,Aleksandr Belenov,FK Ufa,1986.0,RUS,23.0,30.0,53,43.40%
4,Kenneth Vermeer,Feyenoord,1986.0,NED,13.0,17.0,30,43.33%
...,...,...,...,...,...,...,...,...
148,Marko Dmitrović,Eibar,1992.0,SRB,1.0,22.0,23,4.35%
149,Yoan Cardinale,Nice,1994.0,FRA,0.0,12.0,12,0.00%
150,Unai Simón,Athletic Bilbao,1997.0,ESP,0.0,5.0,5,0.00%
151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,NaN,NaN,NaN,NaN,NaN,NaN,last updated:,29.11.2018

In [15]:
# ETL on keepers data by trimming unecessary data off

keeper_df.dropna(axis=0, how='any', inplace=True)
keeper_df.drop(["Current team", "Born"], axis = 1, inplace = True)
keeper_df

            Goalkeeper Country  NotConceded  Conceded PKsFaced   Saves
0         Karlo Letica     CRO          3.0       2.0        5  60.00%
1         Yuri Lodygin     RUS          7.0       6.0       13  53.85%
2          Diego Alves     BRA         25.0      31.0       56  44.64%
3    Aleksandr Belenov     RUS         23.0      30.0       53  43.40%
4      Kenneth Vermeer     NED         13.0      17.0       30  43.33%
..                 ...     ...          ...       ...      ...     ...
146    Thomas Didillon     FRA          1.0      15.0       16   6.25%
147   Thomas Strakosha     ALB          2.0      34.0       36   5.56%
148    Marko Dmitrović     SRB          1.0      22.0       23   4.35%
149     Yoan Cardinale     FRA          0.0      12.0       12   0.00%
150         Unai Simón     ESP          0.0       5.0        5   0.00%

[151 rows x 6 columns]

In [16]:
# More transformations in preparation for merging datasets

keeper_df_rename = keeper_df.rename(columns={'Goalkeeper':'player_name'})
keeper_df_rename

           player_name Country  NotConceded  Conceded PKsFaced   Saves
0         Karlo Letica     CRO          3.0       2.0        5  60.00%
1         Yuri Lodygin     RUS          7.0       6.0       13  53.85%
2          Diego Alves     BRA         25.0      31.0       56  44.64%
3    Aleksandr Belenov     RUS         23.0      30.0       53  43.40%
4      Kenneth Vermeer     NED         13.0      17.0       30  43.33%
..                 ...     ...          ...       ...      ...     ...
146    Thomas Didillon     FRA          1.0      15.0       16   6.25%
147   Thomas Strakosha     ALB          2.0      34.0       36   5.56%
148    Marko Dmitrović     SRB          1.0      22.0       23   4.35%
149     Yoan Cardinale     FRA          0.0      12.0       12   0.00%
150         Unai Simón     ESP          0.0       5.0        5   0.00%

[151 rows x 6 columns]

In [17]:
# Transformation continues to lower case the names to get higher match between datasets

keeper_df_rename['player_name'] = keeper_df_rename['player_name'].str.lower()
keeper_df_rename

           player_name Country  NotConceded  Conceded PKsFaced   Saves
0         karlo letica     CRO          3.0       2.0        5  60.00%
1         yuri lodygin     RUS          7.0       6.0       13  53.85%
2          diego alves     BRA         25.0      31.0       56  44.64%
3    aleksandr belenov     RUS         23.0      30.0       53  43.40%
4      kenneth vermeer     NED         13.0      17.0       30  43.33%
..                 ...     ...          ...       ...      ...     ...
146    thomas didillon     FRA          1.0      15.0       16   6.25%
147   thomas strakosha     ALB          2.0      34.0       36   5.56%
148    marko dmitrović     SRB          1.0      22.0       23   4.35%
149     yoan cardinale     FRA          0.0      12.0       12   0.00%
150         unai simón     ESP          0.0       5.0        5   0.00%

[151 rows x 6 columns]

In [18]:
# merging datasets of players with players attribute along with transformations

merged_players = pd.merge(players_data_new1, playerattr_df_new, how = 'left', on='player_api_id')
merged_players.dropna(axis=0, how='any',inplace=True)
merged_players['player_name'] = merged_players['player_name'].str.lower()
merged_players

,player_name,birthday,height,weight,date,overall_rating,potential,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
player_api_id,,,,,,,,,,,,
505942,aaron appindangoye,1992-02-29 00:00:00,182.88,187,2016-02-18 00:00:00,67.0,71.0,6.0,11.0,10.0,8.0,8.0
155782,aaron cresswell,1989-12-15 00:00:00,170.18,146,2016-04-21 00:00:00,74.0,80.0,14.0,22.0,49.0,22.0,22.0
162549,aaron doran,1991-05-13 00:00:00,170.18,163,2016-01-07 00:00:00,71.0,78.0,16.0,21.0,54.0,21.0,21.0
30572,aaron galindo,1982-05-08 00:00:00,182.88,198,2016-04-21 00:00:00,75.0,82.0,15.0,12.0,65.0,12.0,11.0
23780,aaron hughes,1979-11-08 00:00:00,182.88,154,2015-12-24 00:00:00,78.0,81.0,12.0,20.0,57.0,20.0,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...
192132,zouhaier dhaouadhi,1988-01-01 00:00:00,180.34,159,2016-01-21 00:00:00,64.0,66.0,16.0,10.0,12.0,8.0,8.0
282473,zouhair feddal,1989-01-01 00:00:00,190.50,172,2016-02-04 00:00:00,75.0,79.0,13.0,14.0,12.0,10.0,8.0
26357,zoumana camara,1979-04-03 00:00:00,182.88,168,2015-03-06 00:00:00,77.0,80.0,14.0,21.0,73.0,21.0,21.0
111182,zsolt laczko,1986-12-18 00:00:00,182.88,176,2014-09-18 00:00:00,68.0,79.0,9.0,8.0,5.0,5.0,8.0
39902,zvjezdan misimovic,1982-06-05 00:00:00,180.34,176,2012-08-31 00:00:00,83.0,85.0,9.0,20.0,84.0,20.0,20.0

In [19]:
# merging prior merging results to keepers information

merged_keepers = pd.merge(keeper_df_rename, merged_players, how = 'left', on='player_name')
merged_keepers

,player_name,Country,NotConceded,Conceded,PKsFaced,Saves,birthday,height,weight,date,overall_rating,potential,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,karlo letica,CRO,3.0,2.0,5,60.00%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,yuri lodygin,RUS,7.0,6.0,13,53.85%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,diego alves,BRA,25.0,31.0,56,44.64%,1985-06-24 00:00:00,187.96,183.0,2016-01-28 00:00:00,83.0,86.0,91.0,76.0,76.0,82.0,90.0
3,aleksandr belenov,RUS,23.0,30.0,53,43.40%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,kenneth vermeer,NED,13.0,17.0,30,43.33%,1986-01-10 00:00:00,182.88,172.0,2016-02-19 00:00:00,78.0,82.0,82.0,74.0,70.0,78.0,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,thomas didillon,FRA,1.0,15.0,16,6.25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,thomas strakosha,ALB,2.0,34.0,36,5.56%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,marko dmitrović,SRB,1.0,22.0,23,4.35%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,yoan cardinale,FRA,0.0,12.0,12,0.00%,1994-03-27 00:00:00,180.34,185.0,2016-05-12 00:00:00,70.0,80.0,70.0,69.0,69.0,69.0,73.0
153,unai simón,ESP,0.0,5.0,5,0.00%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
# merging data with FIFA world cup content to identify the national team that each keeper played

final_merged_keepers = pd.merge(merged_keepers, team_df_renamed1, how = 'left', on='Country')
final_merged_keepers

,player_name,Country,NotConceded,Conceded,PKsFaced,Saves,birthday,height,weight,date,overall_rating,potential,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,title,key
0,karlo letica,CRO,3.0,2.0,5,60.00%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Croatia,cro
1,yuri lodygin,RUS,7.0,6.0,13,53.85%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Russia,rus
2,diego alves,BRA,25.0,31.0,56,44.64%,1985-06-24 00:00:00,187.96,183.0,2016-01-28 00:00:00,83.0,86.0,91.0,76.0,76.0,82.0,90.0,Brazil,bra
3,aleksandr belenov,RUS,23.0,30.0,53,43.40%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Russia,rus
4,kenneth vermeer,NED,13.0,17.0,30,43.33%,1986-01-10 00:00:00,182.88,172.0,2016-02-19 00:00:00,78.0,82.0,82.0,74.0,70.0,78.0,85.0,Netherlands,ned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,thomas didillon,FRA,1.0,15.0,16,6.25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,France,fra
150,thomas strakosha,ALB,2.0,34.0,36,5.56%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Albania,alb
151,marko dmitrović,SRB,1.0,22.0,23,4.35%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Serbia,srb
152,yoan cardinale,FRA,0.0,12.0,12,0.00%,1994-03-27 00:00:00,180.34,185.0,2016-05-12 00:00:00,70.0,80.0,70.0,69.0,69.0,69.0,73.0,France,fra
153,unai simón,ESP,0.0,5.0,5,0.00%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spain,esp

In [21]:
# further transformations to drop unecessary columns

final_merged_keepers.drop(["key","birthday"], axis = 1, inplace = True)
final_merged_keepers

,player_name,Country,NotConceded,Conceded,PKsFaced,Saves,height,weight,date,overall_rating,potential,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,title
0,karlo letica,CRO,3.0,2.0,5,60.00%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Croatia
1,yuri lodygin,RUS,7.0,6.0,13,53.85%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Russia
2,diego alves,BRA,25.0,31.0,56,44.64%,187.96,183.0,2016-01-28 00:00:00,83.0,86.0,91.0,76.0,76.0,82.0,90.0,Brazil
3,aleksandr belenov,RUS,23.0,30.0,53,43.40%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Russia
4,kenneth vermeer,NED,13.0,17.0,30,43.33%,182.88,172.0,2016-02-19 00:00:00,78.0,82.0,82.0,74.0,70.0,78.0,85.0,Netherlands
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,thomas didillon,FRA,1.0,15.0,16,6.25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,France
150,thomas strakosha,ALB,2.0,34.0,36,5.56%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Albania
151,marko dmitrović,SRB,1.0,22.0,23,4.35%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Serbia
152,yoan cardinale,FRA,0.0,12.0,12,0.00%,180.34,185.0,2016-05-12 00:00:00,70.0,80.0,70.0,69.0,69.0,69.0,73.0,France
153,unai simón,ESP,0.0,5.0,5,0.00%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spain

In [22]:
# Preparing data to align same structure as in database

final_keepers_renamed = final_merged_keepers.rename(columns={'Country':'country','NotConceded':'not_conceded',\
                                                             'Conceded':'conceded',\
                                                             'PKsFaced':'pksfaced', \
                                                             'Saves':'saves', \
                                                            'gk_diving':'diving','gk_handling': 'handling',\
                                                             'gk_kicking':'kicking','gk_positioning':'positioning', \
                                                            'gk_reflexes':'reflexes'})

final_keepers_renamed

,player_name,country,not_conceded,conceded,pksfaced,saves,height,weight,date,overall_rating,potential,diving,handling,kicking,positioning,reflexes,title
0,karlo letica,CRO,3.0,2.0,5,60.00%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Croatia
1,yuri lodygin,RUS,7.0,6.0,13,53.85%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Russia
2,diego alves,BRA,25.0,31.0,56,44.64%,187.96,183.0,2016-01-28 00:00:00,83.0,86.0,91.0,76.0,76.0,82.0,90.0,Brazil
3,aleksandr belenov,RUS,23.0,30.0,53,43.40%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Russia
4,kenneth vermeer,NED,13.0,17.0,30,43.33%,182.88,172.0,2016-02-19 00:00:00,78.0,82.0,82.0,74.0,70.0,78.0,85.0,Netherlands
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,thomas didillon,FRA,1.0,15.0,16,6.25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,France
150,thomas strakosha,ALB,2.0,34.0,36,5.56%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Albania
151,marko dmitrović,SRB,1.0,22.0,23,4.35%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Serbia
152,yoan cardinale,FRA,0.0,12.0,12,0.00%,180.34,185.0,2016-05-12 00:00:00,70.0,80.0,70.0,69.0,69.0,69.0,73.0,France
153,unai simón,ESP,0.0,5.0,5,0.00%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spain

In [23]:
# creating connection to postgress sql database

connection_string = 'postgres:'+password_db+'@localhost:5432/keepers_db'

engine=create_engine(f"postgresql://{connection_string}")

In [24]:
# verify table if exists
engine.table_names()

['keepers_records']

In [26]:
# push data to table in database
final_keepers_renamed.to_sql(name='keepers_records', con=engine, if_exists='append', index=True)